-- Intro Call Booking — Google Calendar/Meet–backed self-service booking.
--
-- A client opens an unguessable per-deal link (generated by a PM on the deal
-- page), sees slots when the whole project team is free, and books a call. The
-- booking creates a Google Calendar event with a Meet link on the PM's calendar.
--
-- All times that represent a staff working window are stored as LOCAL
-- (Europe/London) wall-clock minutes from midnight — never UTC — so DST is
-- handled purely at slot-projection time. Absolute booking instants are UTC.
--
-- These objects are also self-healed at runtime (ensureIntroCallTables in
-- api/_lib/crm/introCallSlots.js) because migrations are applied by hand in Neon.

-- Per-user availability: one row per (user, weekday). weekday: 0=Mon … 6=Sun.
CREATE TABLE IF NOT EXISTS staff_availability (
  user_email   TEXT NOT NULL REFERENCES users(email) ON DELETE CASCADE,
  weekday      SMALLINT NOT NULL,
  is_working   BOOLEAN NOT NULL DEFAULT TRUE,
  start_minute SMALLINT NOT NULL DEFAULT 600,   -- 10:00
  end_minute   SMALLINT NOT NULL DEFAULT 1020,  -- 17:00
  PRIMARY KEY (user_email, weekday)
);

-- Global booking rules as a singleton JSON on the existing settings row (id=1),
-- mirroring revision_call_url / finance_targets. Code applies defaults when null:
--   { minNoticeHours:24, earliestMinute:600, latestEndMinute:1020,
--     fridayLatestEndMinute:960, lunchStartMinute:780, lunchEndMinute:840,
--     durationMinutes:30, slotGranularityMinutes:30, lookaheadDays:14,
--     timezone:'Europe/London' }
ALTER TABLE settings ADD COLUMN IF NOT EXISTS intro_call_rules JSONB;

-- One shareable booking link per deal (regenerate = revoke + create).
CREATE TABLE IF NOT EXISTS intro_call_links (
  token       TEXT PRIMARY KEY,
  deal_id     TEXT NOT NULL REFERENCES deals(id) ON DELETE CASCADE,
  created_by  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at  TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS intro_call_links_deal_idx ON intro_call_links(deal_id);

-- Confirmed bookings. attendee_emails snapshots the team at booking time;
-- starts_at/ends_at are absolute UTC instants.
CREATE TABLE IF NOT EXISTS intro_call_bookings (
  id              TEXT PRIMARY KEY,
  deal_id         TEXT NOT NULL REFERENCES deals(id) ON DELETE CASCADE,
  link_token      TEXT REFERENCES intro_call_links(token) ON DELETE SET NULL,
  client_name     TEXT NOT NULL,
  client_email    TEXT NOT NULL,
  starts_at       TIMESTAMPTZ NOT NULL,
  ends_at         TIMESTAMPTZ NOT NULL,
  attendee_emails TEXT[] NOT NULL,
  organizer_email TEXT NOT NULL,
  google_event_id TEXT,
  meet_url        TEXT,
  status          TEXT NOT NULL DEFAULT 'confirmed',  -- confirmed | cancelled
  client_timezone TEXT,                               -- IANA tz captured from the client's browser
  reminder_sent_at TIMESTAMPTZ,                       -- client day-of email (9am client-local) sent
  team_task_created_at TIMESTAMPTZ,                   -- team day-of task (9am UK) created
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS intro_call_bookings_deal_idx ON intro_call_bookings(deal_id);
CREATE INDEX IF NOT EXISTS intro_call_bookings_slot_idx ON intro_call_bookings(organizer_email, starts_at);
