-- Producer scheduling calendar + annual leave.
--
-- Three new tables back the "Schedule" section (per-producer calendar, master
-- view, annual-leave tracker and the production dashboard's Amends-to-do list):
--
--   schedule_assignments — one work block for a producer on a video's stage
--     (kind = 'storyboard' | 'production'). Auto-generated by the greedy
--     scheduler in api/_lib/crm/schedule.js from the deal's production schedule
--     + video length, then draggable/extendable in the calendar. A block that
--     can't finish before its delivery deadline (minus an internal-review
--     buffer) is flagged `conflict` and Callum is notified for manual review.
--
--   leave_requests — annual-leave bookings (submitted → approved/denied by
--     Admins & Directors), plus the compulsory Christmas days.
--
--   leave_allowances — per-user allowance config (default 20 days, 6 compulsory
--     over Christmas, renewing on the joining anniversary; part-timers get less).
--
-- All three are also self-healed at runtime by ensureScheduleTables() in
-- api/_lib/crm/schedule.js, so the feature works even before this file is
-- applied to the Neon branch. Apply it anyway to keep the schema authoritative.

CREATE TABLE IF NOT EXISTS schedule_assignments (
  id             TEXT PRIMARY KEY,
  video_id       TEXT NOT NULL REFERENCES project_videos(id) ON DELETE CASCADE,
  deal_id        TEXT NOT NULL REFERENCES deals(id) ON DELETE CASCADE,
  user_email     TEXT NOT NULL,
  kind           TEXT NOT NULL,                 -- 'storyboard' | 'production'
  start_date     DATE NOT NULL,
  end_date       DATE NOT NULL,                 -- inclusive
  duration_days  INTEGER NOT NULL DEFAULT 1,    -- base days from video length
  extended_days  INTEGER NOT NULL DEFAULT 0,    -- manual extension on top
  auto_generated BOOLEAN NOT NULL DEFAULT TRUE, -- false once dragged/extended by hand
  conflict       BOOLEAN NOT NULL DEFAULT FALSE,
  conflict_reason TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- One block per (video, kind, producer) so a re-sync updates rather than dupes.
CREATE UNIQUE INDEX IF NOT EXISTS schedule_assignments_video_kind_user_uidx
  ON schedule_assignments (video_id, kind, user_email);
CREATE INDEX IF NOT EXISTS schedule_assignments_user_idx ON schedule_assignments (user_email);
CREATE INDEX IF NOT EXISTS schedule_assignments_deal_idx ON schedule_assignments (deal_id);
CREATE INDEX IF NOT EXISTS schedule_assignments_dates_idx ON schedule_assignments (start_date, end_date);

CREATE TABLE IF NOT EXISTS leave_requests (
  id          TEXT PRIMARY KEY,
  user_email  TEXT NOT NULL,
  start_date  DATE NOT NULL,
  end_date    DATE NOT NULL,                    -- inclusive
  days        NUMERIC NOT NULL DEFAULT 0,       -- working days (supports 0.5 for part-time)
  kind        TEXT NOT NULL DEFAULT 'annual',   -- 'annual' | 'compulsory'
  note        TEXT,
  status      TEXT NOT NULL DEFAULT 'pending',  -- 'pending' | 'approved' | 'denied'
  decided_by  TEXT,
  decided_at  TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS leave_requests_user_idx ON leave_requests (user_email);
CREATE INDEX IF NOT EXISTS leave_requests_status_idx ON leave_requests (status);
CREATE INDEX IF NOT EXISTS leave_requests_dates_idx ON leave_requests (start_date, end_date);

CREATE TABLE IF NOT EXISTS leave_allowances (
  user_email       TEXT PRIMARY KEY,
  annual_allowance NUMERIC NOT NULL DEFAULT 20, -- total incl. compulsory
  compulsory_days  NUMERIC NOT NULL DEFAULT 6,  -- Christmas break
  anniversary      DATE,                        -- joining anniversary (renewal anchor)
  active           BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
