import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, PoundSterling, PiggyBank, Wallet, Landmark, ChevronDown } from 'lucide-react';
import {
  ResponsiveContainer,
  BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend,
} from 'recharts';
import { BRAND } from '../../theme.js';
import { useStore } from '../../store.jsx';
import { formatGBP, formatProposalNumber, useIsMobile } from '../../utils.js';
import { PerformancePanel } from './PerformanceView.jsx';

const VAT_COLOR = '#F59E0B';
const gbpK = (v) => '£' + Math.round((Number(v) || 0) / 1000) + 'k';
const shortMonth = (key) => {
  const [y, m] = key.split('-').map(Number);
  return new Date(y, m - 1, 1).toLocaleString('en-GB', { month: 'short' });
};

function recentQuarters(n = 8) {
  const out = [];
  const now = new Date();
  let y = now.getFullYear();
  let q = Math.floor(now.getMonth() / 3) + 1;
  for (let i = 0; i < n; i++) {
    out.push(`${y}-Q${q}`);
    q -= 1; if (q < 1) { q = 4; y -= 1; }
  }
  return out;
}

function recentMonths(n = 12) {
  const out = [];
  const now = new Date();
  for (let i = 0; i < n; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    out.push(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`);
  }
  return out;
}
const monthLongLabel = (key) => {
  const [y, m] = key.split('-').map(Number);
  return new Date(y, m - 1, 1).toLocaleString('en-GB', { month: 'long', year: 'numeric' });
};

// Reduce a year's monthly stats (financeStats- or salesFinanceStats-shaped) into
// the cards/chart model for the currently selected period. Shared by the Income
// and Sales breakdowns so they render identically.
function buildFinanceView(fin, { mode, qIdx, monthKey, isCurrentYear, monthIdx, effectiveYear }) {
  const months = fin?.months || [];
  const quarters = fin?.quarters || [];
  const yearTotals = months.reduce((a, m) => ({ net: a.net + m.net, vat: a.vat + m.vat, gross: a.gross + m.gross }), { net: 0, vat: 0, gross: 0 });

  const zero = { net: 0, vat: 0, gross: 0 };
  const displayMonths = mode === 'quarter' ? months.slice(qIdx * 3, qIdx * 3 + 3)
    : mode === 'month' ? months.filter((m) => m.month === monthKey)
    : months;
  const totals = mode === 'quarter' ? (quarters[qIdx] || zero)
    : mode === 'month' ? (months.find((m) => m.month === monthKey) || zero)
    : yearTotals;
  const chart = displayMonths.map((m) => ({ label: shortMonth(m.month), net: m.net, vat: m.vat }));

  const thisMonth = isCurrentYear ? months[monthIdx] : null;
  const thisQuarter = quarters[Math.floor(monthIdx / 3)] || null;
  const periodLabel = mode === 'quarter' ? `Q${qIdx + 1} ${effectiveYear}`
    : mode === 'month' ? monthLongLabel(monthKey)
    : String(effectiveYear);

  return { months, quarters, displayMonths, totals, chart, thisMonth, thisQuarter, periodLabel };
}

export function FinanceView({ onBack, onOpenDeal }) {
  const { state, actions } = useStore();
  const isMobile = useIsMobile();
  const now = new Date();
  const [section, setSection] = useState('income'); // 'income' | 'pending' | 'vat'
  const [perfSection, setPerfSection] = useState('income'); // Performance toggle: 'income' | 'sales'
  const [mode, setMode] = useState('month'); // 'month' | 'quarter' | 'year'
  const [year, setYear] = useState(() => now.getFullYear());
  const [quarterKey, setQuarterKey] = useState(() => recentQuarters(1)[0]); // 'YYYY-Qn'
  const [monthKey, setMonthKey] = useState(() => `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`); // 'YYYY-MM'
  const [loading, setLoading] = useState(true);

  // Which year's data we need (a chosen quarter / month dictates its own year).
  const qYear = Number(quarterKey.split('-Q')[0]);
  const qIdx = Number(quarterKey.split('-Q')[1]) - 1;
  const effectiveYear = mode === 'year' ? year : (mode === 'month' ? Number(monthKey.slice(0, 4)) : qYear);

  // The selected period as the income endpoint expects it: 'YYYY' / 'YYYY-Qn' / 'YYYY-MM'.
  const periodParam = mode === 'year' ? String(year) : (mode === 'quarter' ? quarterKey : monthKey);

  useEffect(() => {
    let active = true;
    setLoading(true);
    actions.loadFinanceStats(effectiveYear).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [actions, effectiveYear]);

  // Income ledger is period-scoped — reload when the selected period changes.
  useEffect(() => { actions.loadIncome(periodParam); }, [actions, periodParam]);

  // Sales breakdown (cash generated by signings + extras) is only needed when the
  // Performance toggle is on Sales — load the year's stats + the period's ledger.
  const isSales = perfSection === 'sales';
  useEffect(() => { if (isSales) actions.loadSalesFinanceStats(effectiveYear); }, [actions, isSales, effectiveYear]);
  useEffect(() => { if (isSales) actions.loadSalesLedger(periodParam); }, [actions, isSales, periodParam]);

  // Outstanding deals aren't period-scoped — load once.
  useEffect(() => { actions.loadPendingPayments(); }, [actions]);

  // Rolling 12-month trend (charts) + imported sheet history — period-independent.
  useEffect(() => { if (!state.trend) actions.loadTrend(12); }, [actions, state.trend]);
  const trend = state.trend;

  const fin = state.financeStats && state.financeStats.year === effectiveYear ? state.financeStats : null;
  const salesFin = state.salesFinanceStats && state.salesFinanceStats.year === effectiveYear ? state.salesFinanceStats : null;
  const salesLedger = state.salesLedger && state.salesLedger.period === periodParam ? state.salesLedger : null;
  const pending = state.pendingPayments;
  const income = state.income && state.income.period === periodParam ? state.income : null;

  const isCurrentYear = effectiveYear === now.getFullYear();
  const monthIdx = now.getMonth();

  const viewArgs = { mode, qIdx, monthKey, isCurrentYear, monthIdx, effectiveYear };
  const view = useMemo(() => buildFinanceView(fin, viewArgs), [fin, mode, qIdx, monthKey, isCurrentYear, monthIdx, effectiveYear]);
  const salesView = useMemo(() => buildFinanceView(salesFin, viewArgs), [salesFin, mode, qIdx, monthKey, isCurrentYear, monthIdx, effectiveYear]);

  // The first finance tab shows Income (cash received) or, when the Performance
  // toggle is on Sales, the cash generated by signings + extras — same layout.
  const firstTab = isSales
    ? { view: salesView, label: 'Sales' }
    : { view, label: 'Income' };

  // Rolling 12-month series for the trend charts (period-independent). The first
  // tab's bar shows cash-in (Income) or cash-generated (Sales); the Sales-vs-PP's
  // tab compares cash-in against new money owed.
  const trendChart = useMemo(() => (trend?.months || []).map((m) => ({
    label: shortMonth(m.month),
    cashIn: m.cashIn,
    cashGenerated: m.cashGenerated,
    pps: m.pps,
  })), [trend]);
  const trendBar = isSales ? 'cashGenerated' : 'cashIn';

  const yearOptions = [now.getFullYear(), now.getFullYear() - 1, now.getFullYear() - 2];

  return (
    <div style={{ padding: isMobile ? '20px 16px' : '40px 24px', maxWidth: 1100, margin: '0 auto' }}>
      <header style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 24, gap: 12, flexWrap: 'wrap' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <button onClick={onBack} className="btn-ghost"><ArrowLeft size={14} /> Back</button>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <PoundSterling size={22} color={BRAND.blue} />
              <h1 style={{ fontSize: 22, fontWeight: 600, margin: 0 }}>Finance</h1>
            </div>
            <p style={{ fontSize: 13, color: BRAND.muted, margin: '2px 0 0' }}>
              Cash received across all customers. Figures are ex-VAT (net); VAT to set aside is shown separately.
            </p>
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
          <Segmented
            value={mode}
            onChange={setMode}
            options={[{ value: 'month', label: 'Month' }, { value: 'quarter', label: 'Quarter' }, { value: 'year', label: 'Year' }]}
          />
          <select
            value={mode === 'year' ? year : mode === 'quarter' ? quarterKey : monthKey}
            onChange={(e) => (mode === 'year' ? setYear(Number(e.target.value)) : mode === 'quarter' ? setQuarterKey(e.target.value) : setMonthKey(e.target.value))}
            style={{ padding: '8px 10px', borderRadius: 8, border: '1px solid ' + BRAND.border, background: 'white', fontSize: 14, color: BRAND.ink }}
          >
            {mode === 'year'
              ? yearOptions.map((y) => <option key={y} value={y}>{y}</option>)
              : mode === 'quarter'
                ? recentQuarters(8).map((k) => { const [y, q] = k.split('-Q'); return <option key={k} value={k}>{`Q${q} ${y}`}</option>; })
                : recentMonths(12).map((k) => <option key={k} value={k}>{monthLongLabel(k)}</option>)}
          </select>
        </div>
      </header>

      {/* Performance — cash pacing vs targets — sits above the finance tabs. Its
          Income/Sales toggle is lifted here so it also drives the first tab. */}
      <PerformancePanel section={perfSection} onSection={setPerfSection} />

      {/* Section tabs — Income (or Sales) / Pending Payments / VAT. */}
      <div style={{ marginBottom: 16 }}>
        <Segmented
          value={section}
          onChange={setSection}
          options={[{ value: 'income', label: firstTab.label }, { value: 'salesvspp', label: "Sales vs PP's" }, { value: 'pending', label: 'Pending Payments' }, { value: 'vat', label: 'VAT' }]}
        />
      </div>

      {section === 'income' && (
        <>
          {/* Headline for the period — net is the lead figure. Income = cash
              received; Sales = cash generated by signings + extras. */}
          <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(2, 1fr)', gap: 12, marginBottom: 16 }}>
            <StatCard icon={Wallet} accent={BRAND.blue}
              label={`${isSales ? 'Cash generated (ex-VAT)' : 'Net revenue (ex-VAT)'} — ${firstTab.view.periodLabel}`}
              value={formatGBP(firstTab.view.totals.net)}
              sub={`${formatGBP(firstTab.view.totals.gross)} gross ${isSales ? 'generated' : 'banked'}`} />
            <StatCard icon={Landmark} accent={BRAND.ink}
              label={`${isSales ? 'Gross generated' : 'Gross banked'} — ${firstTab.view.periodLabel}`}
              value={formatGBP(firstTab.view.totals.gross)}
              sub={`Net + VAT ${isSales ? 'generated' : 'received'}`} />
          </div>

          {/* Rolling 12-month bar chart (period-independent). */}
          <div style={{ background: 'white', border: '1px solid ' + BRAND.border, borderRadius: 12, padding: isMobile ? 12 : 20, marginBottom: 20 }}>
            <h3 style={{ margin: '0 0 12px', fontSize: 13, fontWeight: 700, color: BRAND.muted, textTransform: 'uppercase', letterSpacing: 0.6 }}>
              {isSales ? 'Cash generated (ex-VAT)' : 'Net revenue (ex-VAT)'} — last 12 months
            </h3>
            {!trend ? (
              <div style={{ height: 320, display: 'flex', alignItems: 'center', justifyContent: 'center', color: BRAND.muted, fontSize: 14 }}>Loading…</div>
            ) : (
              <ResponsiveContainer width="100%" height={320}>
                <BarChart data={trendChart} margin={{ top: 8, right: 16, left: 0, bottom: 8 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke={BRAND.border} />
                  <XAxis dataKey="label" tick={{ fontSize: 12, fill: BRAND.muted }} />
                  <YAxis tickFormatter={gbpK} tick={{ fontSize: 12, fill: BRAND.muted }} width={56} />
                  <Tooltip formatter={(v, n) => [formatGBP(v), n]} cursor={{ fill: 'rgba(43,184,230,0.06)' }} />
                  <Legend wrapperStyle={{ fontSize: 12 }} />
                  <Bar dataKey={trendBar} name={isSales ? 'Cash generated (ex-VAT)' : 'Net revenue (ex-VAT)'} fill={BRAND.blue} radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>

          {/* Itemised ledger — payments received (Income) or signings + extras (Sales). */}
          {isSales ? (
            <SalesLedgerPanel ledger={salesLedger} onOpenDeal={onOpenDeal} isMobile={isMobile} periodLabel={firstTab.view.periodLabel} />
          ) : (
            <IncomePayments income={income} onOpenDeal={onOpenDeal} isMobile={isMobile} periodLabel={firstTab.view.periodLabel} />
          )}
        </>
      )}

      {section === 'salesvspp' && (
        <SalesVsPpTab trend={trend} trendChart={trendChart} isMobile={isMobile} actions={actions} history={state.salesHistory} />
      )}

      {section === 'vat' && (
        <>
          {/* VAT-to-save is the headline ask. */}
          <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : (mode === 'year' ? 'repeat(2, 1fr)' : '1fr'), gap: 12, marginBottom: 16 }}>
            {mode !== 'year' ? (
              <StatCard icon={PiggyBank} accent={VAT_COLOR} label={`VAT to set aside — ${view.periodLabel}`} value={formatGBP(view.totals.vat)} sub={`Set aside for ${view.periodLabel}`} />
            ) : (
              <>
                <StatCard icon={PiggyBank} accent={VAT_COLOR} label={view.thisMonth ? `VAT to set aside — ${shortMonth(view.thisMonth.month)}` : `VAT to set aside — ${effectiveYear}`} value={formatGBP(view.thisMonth ? view.thisMonth.vat : view.totals.vat)} sub={view.thisMonth ? 'From cash banked this month' : 'Total for the year'} />
                <QuarterMenuCard
                  quarters={view.quarters}
                  currentIdx={isCurrentYear ? Math.floor(monthIdx / 3) : -1}
                  label={isCurrentYear && view.thisQuarter ? `VAT — ${view.thisQuarter.label}` : `VAT — ${effectiveYear}`}
                  value={formatGBP(isCurrentYear && view.thisQuarter ? view.thisQuarter.vat : view.totals.vat)}
                  onPick={(i) => { setQuarterKey(`${effectiveYear}-Q${i + 1}`); setMode('quarter'); }}
                />
              </>
            )}
          </div>

          {/* Monthly breakdown table. */}
          <div style={{ background: 'white', border: '1px solid ' + BRAND.border, borderRadius: 12, padding: isMobile ? 12 : 20 }}>
            <h3 style={{ margin: '0 0 12px', fontSize: 13, fontWeight: 700, color: BRAND.muted, textTransform: 'uppercase', letterSpacing: 0.6 }}>
              Monthly breakdown — {view.periodLabel}
            </h3>
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
                <thead>
                  <tr style={{ textAlign: 'right', color: BRAND.muted, fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.4 }}>
                    <th style={{ textAlign: 'left', padding: '8px 8px' }}>Month</th>
                    <th style={{ padding: '8px 8px' }}>Net (ex-VAT)</th>
                    <th style={{ padding: '8px 8px', color: VAT_COLOR }}>VAT to save</th>
                    <th style={{ padding: '8px 8px' }}>Gross</th>
                  </tr>
                </thead>
                <tbody>
                  {view.displayMonths.map((m) => {
                    const isThis = isCurrentYear && m.month === `${effectiveYear}-${String(monthIdx + 1).padStart(2, '0')}`;
                    return (
                      <tr key={m.month} style={{ borderTop: '1px solid ' + BRAND.border, background: isThis ? '#F4FBFE' : 'transparent' }}>
                        <td style={{ textAlign: 'left', padding: '8px 8px', fontWeight: isThis ? 700 : 500 }}>
                          {shortMonth(m.month)}{isThis ? ' · this month' : ''}
                        </td>
                        <td style={{ textAlign: 'right', padding: '8px 8px' }}>{formatGBP(m.net)}</td>
                        <td style={{ textAlign: 'right', padding: '8px 8px', fontWeight: 600, color: m.vat > 0 ? VAT_COLOR : BRAND.muted }}>{formatGBP(m.vat)}</td>
                        <td style={{ textAlign: 'right', padding: '8px 8px', color: BRAND.muted }}>{formatGBP(m.gross)}</td>
                      </tr>
                    );
                  })}
                </tbody>
                {mode !== 'month' && (
                  <tfoot>
                    <tr style={{ borderTop: '2px solid ' + BRAND.border, fontWeight: 700 }}>
                      <td style={{ textAlign: 'left', padding: '10px 8px' }}>Total {view.periodLabel}</td>
                      <td style={{ textAlign: 'right', padding: '10px 8px' }}>{formatGBP(view.totals.net)}</td>
                      <td style={{ textAlign: 'right', padding: '10px 8px', color: VAT_COLOR }}>{formatGBP(view.totals.vat)}</td>
                      <td style={{ textAlign: 'right', padding: '10px 8px' }}>{formatGBP(view.totals.gross)}</td>
                    </tr>
                  </tfoot>
                )}
              </table>
            </div>
          </div>
        </>
      )}

      {section === 'pending' && (
        <>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: 12, marginBottom: 16 }}>
            <StatCard icon={PoundSterling} accent={BRAND.ink} label="Outstanding — all customers" value={formatGBP(fin ? fin.outstanding : 0)} sub="Still to collect (inc VAT)" />
          </div>
          {/* Pending Payments — outstanding signed deals, split PO vs normal. */}
          <PendingPayments pending={pending} onOpenDeal={onOpenDeal} isMobile={isMobile} />
        </>
      )}
    </div>
  );
}

// Payment-type labels mirroring the sales sheet's "Invoice Type" column. A
// 50/50 deal shows a deposit + final line; "full" / PO deals show one line.
const PAYMENT_TYPE_META = {
  deposit: { label: '50% Deposit', color: '#B45309', bg: '#FFFBEB' },
  final: { label: '50% Final', color: '#1D4ED8', bg: '#EFF6FF' },
  full: { label: 'Full up front', color: '#15803D', bg: '#ECFDF3' },
  po: { label: 'Purchase order', color: '#6D28D9', bg: '#F5F3FF' },
  extra: { label: 'Extra', color: '#C2410C', bg: '#FFF7ED' },
};

function PendingPayments({ pending, onOpenDeal, isMobile }) {
  return (
    <div style={{ background: 'white', border: '1px solid ' + BRAND.border, borderRadius: 12, padding: isMobile ? 12 : 20, marginTop: 20 }}>
      <h3 style={{ margin: '0 0 4px', fontSize: 13, fontWeight: 700, color: BRAND.muted, textTransform: 'uppercase', letterSpacing: 0.6 }}>
        Pending Payments
      </h3>
      <p style={{ margin: '0 0 16px', fontSize: 12, color: BRAND.muted }}>
        Outstanding balances on signed deals — shown ex-VAT (net). 50/50 deals split into the invoiced deposit (awaiting payment) and the final still to invoice.
      </p>
      {!pending ? (
        <div style={{ padding: '12px 4px', fontSize: 13, color: BRAND.muted }}>Loading…</div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <PendingGroup
            title="Invoiced work"
            note="Paid on project milestones / completion"
            rows={pending.normal}
            total={pending.totals.normal}
            accent={BRAND.blue}
            onOpenDeal={onOpenDeal}
          />
          <PendingGroup
            title="Purchase Orders"
            note="Paid regardless of project stage"
            rows={pending.po}
            total={pending.totals.po}
            accent="#8B5CF6"
            onOpenDeal={onOpenDeal}
          />
        </div>
      )}
    </div>
  );
}

function PendingGroup({ title, note, rows, total, accent, onOpenDeal }) {
  return (
    <div style={{ border: '1px solid ' + BRAND.border, borderRadius: 10, overflow: 'hidden' }}>
      <div style={{ padding: '10px 14px', borderBottom: '1px solid ' + BRAND.border, borderLeft: `3px solid ${accent}` }}>
        <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 8 }}>
          <span style={{ fontSize: 14, fontWeight: 700, color: BRAND.ink }}>{title}</span>
          <span style={{ fontSize: 16, fontWeight: 700, color: BRAND.ink }}>{formatGBP(total)}</span>
        </div>
        <div style={{ fontSize: 12, color: BRAND.muted, marginTop: 2 }}>{note} · {rows.length} {rows.length === 1 ? 'deal' : 'deals'}</div>
      </div>
      {rows.length === 0 ? (
        <div style={{ padding: 14, fontSize: 13, color: BRAND.muted, fontStyle: 'italic' }}>Nothing outstanding.</div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          {rows.map((d) => (
            <PendingRow key={d.dealId} d={d} onOpenDeal={onOpenDeal} />
          ))}
        </div>
      )}
    </div>
  );
}

// Where each payment came from, for the Income ledger's source badge.
const SOURCE_META = {
  stripe: { label: 'Card', color: '#1D4ED8', bg: '#EFF6FF' },
  partner: { label: 'Partner', color: '#6D28D9', bg: '#F5F3FF' },
  manual: { label: 'Manual', color: '#B45309', bg: '#FFFBEB' },
  invoice: { label: 'Invoice', color: '#15803D', bg: '#ECFDF3' },
  billing: { label: 'Billing', color: '#0E7490', bg: '#ECFEFF' },
};

function SourceBadge({ source }) {
  const m = SOURCE_META[source] || SOURCE_META.manual;
  return (
    <span style={{ fontSize: 10, fontWeight: 700, color: m.color, background: m.bg, padding: '1px 6px', borderRadius: 4, textTransform: 'uppercase', letterSpacing: 0.3, whiteSpace: 'nowrap', flexShrink: 0 }}>
      {m.label}
    </span>
  );
}

// Income — a flat, newest-first ledger of payments received in the selected
// period. Mirrors the Pending Payments panel visually but each row is one
// payment (money in) rather than an outstanding deal balance.
function IncomePayments({ income, onOpenDeal, isMobile, periodLabel }) {
  return (
    <div style={{ background: 'white', border: '1px solid ' + BRAND.border, borderRadius: 12, padding: isMobile ? 12 : 20, marginTop: 4 }}>
      <h3 style={{ margin: '0 0 4px', fontSize: 13, fontWeight: 700, color: BRAND.muted, textTransform: 'uppercase', letterSpacing: 0.6 }}>
        Income — {periodLabel}
      </h3>
      <p style={{ margin: '0 0 16px', fontSize: 12, color: BRAND.muted }}>
        Payments received in {periodLabel}, shown ex-VAT (net). Newest first.
      </p>
      {!income ? (
        <div style={{ padding: '12px 4px', fontSize: 13, color: BRAND.muted }}>Loading…</div>
      ) : income.rows.length === 0 ? (
        <div style={{ border: '1px solid ' + BRAND.border, borderRadius: 10, padding: 14, fontSize: 13, color: BRAND.muted, fontStyle: 'italic' }}>
          No payments in this period.
        </div>
      ) : (
        <div style={{ border: '1px solid ' + BRAND.border, borderRadius: 10, overflow: 'hidden' }}>
          <div style={{ padding: '10px 14px', borderBottom: '1px solid ' + BRAND.border, borderLeft: `3px solid ${BRAND.blue}`, display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 8 }}>
            <span style={{ fontSize: 12, color: BRAND.muted }}>{income.rows.length} {income.rows.length === 1 ? 'payment' : 'payments'}</span>
            <span style={{ fontSize: 16, fontWeight: 700, color: BRAND.ink }}>{formatGBP(income.total)}</span>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column' }}>
            {income.rows.map((r, i) => (
              <IncomeRow key={i} r={r} onOpenDeal={onOpenDeal} />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function IncomeRow({ r, onOpenDeal }) {
  const name = r.company || 'Unattributed';
  const number = r.number ? formatProposalNumber(r.number) : '';
  const date = r.paidAt ? new Date(r.paidAt).toLocaleDateString('en-GB') : '';
  const canOpen = !!(onOpenDeal && r.dealId);
  const open = () => { if (canOpen) onOpenDeal(r.dealId); };
  return (
    <div
      role={canOpen ? 'button' : undefined}
      tabIndex={canOpen ? 0 : undefined}
      onClick={open}
      onKeyDown={(e) => { if (canOpen && (e.key === 'Enter' || e.key === ' ')) { e.preventDefault(); open(); } }}
      onMouseEnter={(e) => { if (canOpen) e.currentTarget.style.background = BRAND.paper; }}
      onMouseLeave={(e) => { if (canOpen) e.currentTarget.style.background = 'white'; }}
      style={{ borderTop: '1px solid ' + BRAND.border, background: 'white', cursor: canOpen ? 'pointer' : 'default', padding: '8px 14px' }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, flex: 1, minWidth: 0 }}>
          <span style={{ fontSize: 13, fontWeight: 600, color: BRAND.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
            {name}
          </span>
          {number && <span style={{ fontSize: 11, fontWeight: 600, color: BRAND.muted, flexShrink: 0 }}>{number}</span>}
          <SourceBadge source={r.source} />
          {date && <span style={{ fontSize: 12, color: BRAND.muted, flexShrink: 0 }}>{date}</span>}
        </div>
        <div style={{ fontSize: 14, fontWeight: 700, color: BRAND.ink, flexShrink: 0 }}>{formatGBP(r.net)}</div>
      </div>
    </div>
  );
}

// Where a sales-ledger row came from: a deal signing or an ad-hoc extra.
const SALES_SOURCE_META = {
  signed: { label: 'Signed', color: '#15803D', bg: '#ECFDF3' },
  extra: { label: 'Extra', color: '#C2410C', bg: '#FFF7ED' },
};

function SalesSourceBadge({ source }) {
  const m = SALES_SOURCE_META[source] || SALES_SOURCE_META.signed;
  return (
    <span style={{ fontSize: 10, fontWeight: 700, color: m.color, background: m.bg, padding: '1px 6px', borderRadius: 4, textTransform: 'uppercase', letterSpacing: 0.3, whiteSpace: 'nowrap', flexShrink: 0 }}>
      {m.label}
    </span>
  );
}

// Sales — a flat, newest-first ledger of cash GENERATED in the period: one row
// per deal signed (its net signed value) and one per extra. Mirrors the Income
// ledger so the two breakdowns read identically.
function SalesLedgerPanel({ ledger, onOpenDeal, isMobile, periodLabel }) {
  return (
    <div style={{ background: 'white', border: '1px solid ' + BRAND.border, borderRadius: 12, padding: isMobile ? 12 : 20, marginTop: 4 }}>
      <h3 style={{ margin: '0 0 4px', fontSize: 13, fontWeight: 700, color: BRAND.muted, textTransform: 'uppercase', letterSpacing: 0.6 }}>
        Cash generated — {periodLabel}
      </h3>
      <p style={{ margin: '0 0 16px', fontSize: 12, color: BRAND.muted }}>
        New business signed and extras added in {periodLabel}, shown ex-VAT (net). Newest first.
      </p>
      {!ledger ? (
        <div style={{ padding: '12px 4px', fontSize: 13, color: BRAND.muted }}>Loading…</div>
      ) : ledger.rows.length === 0 ? (
        <div style={{ border: '1px solid ' + BRAND.border, borderRadius: 10, padding: 14, fontSize: 13, color: BRAND.muted, fontStyle: 'italic' }}>
          No sales in this period.
        </div>
      ) : (
        <div style={{ border: '1px solid ' + BRAND.border, borderRadius: 10, overflow: 'hidden' }}>
          <div style={{ padding: '10px 14px', borderBottom: '1px solid ' + BRAND.border, borderLeft: `3px solid ${BRAND.blue}`, display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 8 }}>
            <span style={{ fontSize: 12, color: BRAND.muted }}>{ledger.rows.length} {ledger.rows.length === 1 ? 'item' : 'items'}</span>
            <span style={{ fontSize: 16, fontWeight: 700, color: BRAND.ink }}>{formatGBP(ledger.total)}</span>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column' }}>
            {ledger.rows.map((r, i) => (
              <SalesRow key={i} r={r} onOpenDeal={onOpenDeal} />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function SalesRow({ r, onOpenDeal }) {
  const name = r.company || (r.source === 'extra' ? (r.label || 'Extra') : 'Unattributed');
  const number = r.number ? formatProposalNumber(r.number) : '';
  const date = r.at ? new Date(r.at).toLocaleDateString('en-GB') : '';
  const canOpen = !!(onOpenDeal && r.dealId);
  const open = () => { if (canOpen) onOpenDeal(r.dealId); };
  return (
    <div
      role={canOpen ? 'button' : undefined}
      tabIndex={canOpen ? 0 : undefined}
      onClick={open}
      onKeyDown={(e) => { if (canOpen && (e.key === 'Enter' || e.key === ' ')) { e.preventDefault(); open(); } }}
      onMouseEnter={(e) => { if (canOpen) e.currentTarget.style.background = BRAND.paper; }}
      onMouseLeave={(e) => { if (canOpen) e.currentTarget.style.background = 'white'; }}
      style={{ borderTop: '1px solid ' + BRAND.border, background: 'white', cursor: canOpen ? 'pointer' : 'default', padding: '8px 14px' }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, flex: 1, minWidth: 0 }}>
          <span style={{ fontSize: 13, fontWeight: 600, color: BRAND.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
            {name}
          </span>
          {number && <span style={{ fontSize: 11, fontWeight: 600, color: BRAND.muted, flexShrink: 0 }}>{number}</span>}
          <SalesSourceBadge source={r.source} />
          {r.source === 'extra' && r.company && r.label && (
            <span style={{ fontSize: 12, color: BRAND.muted, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', minWidth: 0 }}>
              {r.label}
            </span>
          )}
          {date && <span style={{ fontSize: 12, color: BRAND.muted, flexShrink: 0 }}>{date}</span>}
        </div>
        <div style={{ fontSize: 14, fontWeight: 700, color: BRAND.ink, flexShrink: 0 }}>{formatGBP(r.net)}</div>
      </div>
    </div>
  );
}

function PaymentBadge({ type }) {
  const m = PAYMENT_TYPE_META[type] || PAYMENT_TYPE_META.full;
  return (
    <span style={{ fontSize: 10, fontWeight: 700, color: m.color, background: m.bg, padding: '1px 6px', borderRadius: 4, textTransform: 'uppercase', letterSpacing: 0.3, whiteSpace: 'nowrap', flexShrink: 0 }}>
      {m.label}
    </span>
  );
}

function PendingRow({ d, onOpenDeal }) {
  const name = d.company || d.title || 'Untitled deal';
  // Only keep the deal title as a second line when it adds something beyond the
  // company name (avoids showing e.g. "Beyond PR" twice).
  const subtitle = d.company && d.title && d.title !== d.company ? d.title : null;
  const number = d.number ? formatProposalNumber(d.number) : '';
  const lines = d.lines && d.lines.length ? d.lines : [{ type: 'full', amount: d.outstanding }];
  const single = lines.length === 1;
  const single0 = single ? lines[0] : null;
  const showCommitted = Math.abs((d.committed || 0) - (d.outstanding || 0)) > 0.005;
  const open = () => onOpenDeal && onOpenDeal(d.dealId);
  return (
    <div
      role="button"
      tabIndex={0}
      onClick={open}
      onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); open(); } }}
      onMouseEnter={(e) => { e.currentTarget.style.background = BRAND.paper; }}
      onMouseLeave={(e) => { e.currentTarget.style.background = 'white'; }}
      style={{ borderTop: '1px solid ' + BRAND.border, background: 'white', cursor: onOpenDeal ? 'pointer' : 'default', padding: '8px 14px' }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, flex: 1, minWidth: 0 }}>
          <span style={{ fontSize: 13, fontWeight: 600, color: BRAND.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
            {name}
          </span>
          {number && <span style={{ fontSize: 11, fontWeight: 600, color: BRAND.muted, flexShrink: 0 }}>{number}</span>}
          {single && <PaymentBadge type={single0.type} />}
          {single && single0.label && (
            <span style={{ fontSize: 12, color: BRAND.muted, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', minWidth: 0 }}>
              {single0.label}
            </span>
          )}
        </div>
        <div style={{ textAlign: 'right', flexShrink: 0 }}>
          <div style={{ fontSize: 14, fontWeight: 700, color: BRAND.ink }}>{formatGBP(d.outstanding)}</div>
          {showCommitted && <div style={{ fontSize: 11, color: BRAND.muted }}>of {formatGBP(d.committed)}</div>}
        </div>
      </div>
      {subtitle && (
        <div style={{ fontSize: 12, color: BRAND.muted, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
          {subtitle}
        </div>
      )}
      {!single && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 3, marginTop: 6 }}>
          {lines.map((l, i) => (
            <div key={i} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 }}>
              <span style={{ display: 'flex', alignItems: 'center', gap: 6, minWidth: 0 }}>
                <PaymentBadge type={l.type} />
                {l.label && (
                  <span style={{ fontSize: 12, color: BRAND.muted, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', minWidth: 0 }}>
                    {l.label}
                  </span>
                )}
              </span>
              <span style={{ display: 'flex', alignItems: 'center', gap: 6, flexShrink: 0 }}>
                <span style={{ fontSize: 12, fontWeight: 600, color: BRAND.ink }}>{formatGBP(l.amount)}</span>
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

const PPS_COLOR = '#F59E0B';
const MONTH_ABBR = { jan: 1, feb: 2, mar: 3, apr: 4, may: 5, jun: 6, jul: 7, aug: 8, sep: 9, oct: 10, nov: 11, dec: 12 };

// Parse a sheet "Month" cell into 'YYYY-MM'. Accepts 'Sep-16', 'Sep 2016',
// 'September 2016', '2016-09', '2016-09-01'. Returns null if unrecognised.
function parseMonthCell(raw) {
  const s = String(raw || '').trim();
  if (/^\d{4}-\d{2}/.test(s)) return s.slice(0, 7);
  const m = s.match(/^([A-Za-z]{3,})[-\s/]+(\d{2,4})$/);
  if (m) {
    const mi = MONTH_ABBR[m[1].slice(0, 3).toLowerCase()];
    if (mi) {
      let y = Number(m[2]);
      if (y < 100) y += 2000;
      return `${y}-${String(mi).padStart(2, '0')}`;
    }
  }
  return null;
}

const parseMoney = (raw) => Number(String(raw ?? '').replace(/[£,\s]/g, '')) || 0;

// Parse pasted TSV/CSV (Month, Sales, PP's) into normalised history rows,
// skipping a header row and anything without a recognisable month.
function parseHistoryPaste(text) {
  const out = [];
  for (const line of String(text || '').split(/\r?\n/)) {
    if (!line.trim()) continue;
    const cells = line.split(/\t|,/).map((c) => c.trim());
    const month = parseMonthCell(cells[0]);
    if (!month) continue; // header or junk
    out.push({ month, sales: parseMoney(cells[1]), pps: parseMoney(cells[2]) });
  }
  return out;
}

// Sales vs PP's — cash received each month against the new money owed created
// that month, over the last 12 months. The owed line is tomorrow's income, so
// the gap reads as the forward pipeline. Admins can backfill pre-CRM months from
// the Live Sales Sheet.
function SalesVsPpTab({ trend, trendChart, isMobile, actions, history }) {
  const totals = (trend?.months || []).reduce(
    (a, m) => ({ cashIn: a.cashIn + (m.cashIn || 0), pps: a.pps + (m.pps || 0) }),
    { cashIn: 0, pps: 0 },
  );
  return (
    <>
      <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(2, 1fr)', gap: 12, marginBottom: 16 }}>
        <StatCard icon={Wallet} accent={BRAND.blue} label="Cash in — last 12 months" value={formatGBP(totals.cashIn)} sub="Payments received (ex-VAT)" />
        <StatCard icon={PoundSterling} accent={PPS_COLOR} label="New money owed — last 12 months" value={formatGBP(totals.pps)} sub="Created by signings + extras — future income" />
      </div>

      <div style={{ background: 'white', border: '1px solid ' + BRAND.border, borderRadius: 12, padding: isMobile ? 12 : 20, marginBottom: 20 }}>
        <h3 style={{ margin: '0 0 4px', fontSize: 13, fontWeight: 700, color: BRAND.muted, textTransform: 'uppercase', letterSpacing: 0.6 }}>
          Sales vs PP's — last 12 months
        </h3>
        <p style={{ margin: '0 0 12px', fontSize: 12, color: BRAND.muted }}>
          Cash received each month vs new money owed created that month (ex-VAT). The owed line previews future income.
        </p>
        {!trend ? (
          <div style={{ height: 340, display: 'flex', alignItems: 'center', justifyContent: 'center', color: BRAND.muted, fontSize: 14 }}>Loading…</div>
        ) : (
          <ResponsiveContainer width="100%" height={340}>
            <LineChart data={trendChart} margin={{ top: 8, right: 16, left: 0, bottom: 8 }}>
              <CartesianGrid strokeDasharray="3 3" stroke={BRAND.border} />
              <XAxis dataKey="label" tick={{ fontSize: 12, fill: BRAND.muted }} />
              <YAxis tickFormatter={gbpK} tick={{ fontSize: 12, fill: BRAND.muted }} width={56} />
              <Tooltip formatter={(v, n) => [formatGBP(v), n]} cursor={{ stroke: BRAND.border }} />
              <Legend wrapperStyle={{ fontSize: 12 }} />
              <Line type="monotone" dataKey="cashIn" name="Sales (cash in)" stroke={BRAND.blue} strokeWidth={2.5} dot={false} />
              <Line type="monotone" dataKey="pps" name="PP's (money owed)" stroke={PPS_COLOR} strokeWidth={2.5} dot={false} />
            </LineChart>
          </ResponsiveContainer>
        )}
      </div>

      <ImportHistoryPanel actions={actions} history={history} isMobile={isMobile} />
    </>
  );
}

function ImportHistoryPanel({ actions, history, isMobile }) {
  const [open, setOpen] = useState(false);
  const [text, setText] = useState('');
  const [mode, setMode] = useState('merge');
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState(null);

  useEffect(() => { if (open && history == null) actions.loadSalesHistory(); }, [open, history, actions]);

  const parsed = useMemo(() => parseHistoryPaste(text), [text]);

  const submit = async () => {
    if (!parsed.length || busy) return;
    setBusy(true); setResult(null);
    try {
      const data = await actions.importSalesHistory(parsed, mode);
      await actions.loadTrend(12);
      setResult({ ok: true, saved: data?.saved ?? parsed.length });
      setText('');
    } catch {
      setResult({ ok: false });
    } finally {
      setBusy(false);
    }
  };

  return (
    <div style={{ background: 'white', border: '1px solid ' + BRAND.border, borderRadius: 12, padding: isMobile ? 12 : 20 }}>
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        style={{ display: 'flex', alignItems: 'center', gap: 8, width: '100%', background: 'none', border: 'none', cursor: 'pointer', padding: 0, textAlign: 'left' }}
      >
        <ChevronDown size={16} color={BRAND.muted} style={{ transform: open ? 'rotate(0deg)' : 'rotate(-90deg)', transition: 'transform 0.15s' }} />
        <span style={{ fontSize: 13, fontWeight: 700, color: BRAND.muted, textTransform: 'uppercase', letterSpacing: 0.6 }}>
          Import Live Sales Sheet history
        </span>
        {history && history.length > 0 && (
          <span style={{ fontSize: 12, color: BRAND.muted, fontWeight: 500 }}>· {history.length} months stored</span>
        )}
      </button>

      {open && (
        <div style={{ marginTop: 14 }}>
          <p style={{ margin: '0 0 10px', fontSize: 12, color: BRAND.muted }}>
            Paste three columns — <strong>Month, Sales (cash in), PP's (money owed)</strong> — straight from the sheet (tab or comma separated).
            Months are read as <code>Sep-16</code> or <code>2016-09</code>; a header row is ignored. These override the computed figures for those months.
          </p>
          <textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder={'Sep-16\t6695\t1130\nOct-16\t5838\t1650\n…'}
            rows={8}
            style={{ width: '100%', boxSizing: 'border-box', padding: 10, borderRadius: 8, border: '1px solid ' + BRAND.border, fontSize: 13, fontFamily: 'monospace', resize: 'vertical' }}
          />
          <div style={{ display: 'flex', alignItems: 'center', gap: 14, flexWrap: 'wrap', marginTop: 12 }}>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, color: BRAND.ink, cursor: 'pointer' }}>
              <input type="radio" checked={mode === 'merge'} onChange={() => setMode('merge')} /> Merge (update/add)
            </label>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, color: BRAND.ink, cursor: 'pointer' }}>
              <input type="radio" checked={mode === 'replace'} onChange={() => setMode('replace')} /> Replace all
            </label>
            <span style={{ fontSize: 12, color: BRAND.muted }}>{parsed.length} {parsed.length === 1 ? 'month' : 'months'} detected</span>
            <button onClick={submit} className="btn" disabled={!parsed.length || busy} style={{ marginLeft: 'auto' }}>
              {busy ? 'Importing…' : 'Import history'}
            </button>
          </div>
          {result && (
            <div style={{ marginTop: 10, fontSize: 13, color: result.ok ? '#15803D' : '#EF4444' }}>
              {result.ok ? `Imported ${result.saved} months — charts updated.` : 'Import failed — please try again.'}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function Segmented({ value, onChange, options }) {
  return (
    <div style={{ display: 'inline-flex', border: '1px solid ' + BRAND.border, borderRadius: 8, overflow: 'hidden', background: 'white' }}>
      {options.map((o) => (
        <button
          key={o.value}
          onClick={() => onChange(o.value)}
          style={{
            padding: '8px 14px', border: 'none', cursor: 'pointer', fontSize: 14,
            fontWeight: value === o.value ? 600 : 500,
            background: value === o.value ? BRAND.blue : 'white',
            color: value === o.value ? 'white' : BRAND.ink,
          }}
        >
          {o.label}
        </button>
      ))}
    </div>
  );
}

// The "VAT — Q{n}" headline card, but clickable: opens a dropdown of all four
// quarters (VAT + net) to jump into a quarter view, replacing the old always-on
// quarters strip.
function QuarterMenuCard({ quarters, currentIdx, label, value, onPick }) {
  const [open, setOpen] = useState(false);
  const ref = useRef(null);
  useEffect(() => {
    if (!open) return;
    const onDown = (e) => { if (ref.current && !ref.current.contains(e.target)) setOpen(false); };
    const onEsc = (e) => { if (e.key === 'Escape') setOpen(false); };
    document.addEventListener('mousedown', onDown);
    document.addEventListener('keydown', onEsc);
    return () => { document.removeEventListener('mousedown', onDown); document.removeEventListener('keydown', onEsc); };
  }, [open]);
  const list = quarters || [];
  return (
    <div ref={ref} style={{ position: 'relative' }}>
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        aria-haspopup="menu"
        aria-expanded={open}
        style={{
          width: '100%', height: '100%', textAlign: 'left', cursor: 'pointer', boxSizing: 'border-box',
          background: 'white', border: '1px solid ' + (open ? BRAND.blue : BRAND.border),
          borderLeft: `3px solid ${VAT_COLOR}`, borderRadius: 10, padding: 16,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, fontWeight: 700, color: BRAND.muted, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 8 }}>
          <Landmark size={14} color={VAT_COLOR} />
          <span style={{ flex: 1 }}>{label}</span>
          <ChevronDown size={14} style={{ opacity: 0.6, transform: open ? 'rotate(180deg)' : 'none', transition: 'transform 0.15s' }} />
        </div>
        <div style={{ fontSize: 24, fontWeight: 700, color: BRAND.ink }}>{value}</div>
        <div style={{ fontSize: 12, color: BRAND.muted, marginTop: 4 }}>Click to view any quarter</div>
      </button>
      {open && list.length > 0 && (
        <div
          role="menu"
          style={{
            position: 'absolute', top: 'calc(100% + 6px)', left: 0, right: 0,
            background: 'white', border: '1px solid ' + BRAND.border, borderRadius: 10,
            boxShadow: '0 8px 24px rgba(15, 42, 61, 0.12)', padding: 6, zIndex: 50,
            display: 'flex', flexDirection: 'column', gap: 2,
          }}
        >
          {list.map((q, i) => (
            <button
              key={q.label}
              type="button"
              role="menuitem"
              onClick={() => { onPick(i); setOpen(false); }}
              onMouseEnter={(e) => { e.currentTarget.style.background = BRAND.paper; }}
              onMouseLeave={(e) => { e.currentTarget.style.background = i === currentIdx ? '#F4FBFE' : 'transparent'; }}
              style={{
                display: 'flex', alignItems: 'baseline', gap: 8, width: '100%',
                padding: '8px 10px', border: 'none', borderRadius: 8, cursor: 'pointer',
                background: i === currentIdx ? '#F4FBFE' : 'transparent', textAlign: 'left',
              }}
            >
              <span style={{ flex: 1, fontSize: 14, fontWeight: 600, color: BRAND.ink }}>
                {q.label}{i === currentIdx ? ' · now' : ''}
              </span>
              <span style={{ fontSize: 14, fontWeight: 700, color: VAT_COLOR }}>{formatGBP(q.vat)}</span>
              <span style={{ fontSize: 12, color: BRAND.muted }}>{formatGBP(q.net)} net</span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

function StatCard({ icon: Icon, label, value, sub, accent }) {
  return (
    <div style={{ background: 'white', border: '1px solid ' + BRAND.border, borderLeft: `3px solid ${accent || BRAND.blue}`, borderRadius: 10, padding: 16 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, fontWeight: 700, color: BRAND.muted, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 8 }}>
        {Icon && <Icon size={14} color={accent || BRAND.muted} />}
        <span>{label}</span>
      </div>
      <div style={{ fontSize: 24, fontWeight: 700, color: BRAND.ink }}>{value}</div>
      {sub && <div style={{ fontSize: 12, color: BRAND.muted, marginTop: 4 }}>{sub}</div>}
    </div>
  );
}
